const fs = require('fs');
const path = require('path');

const AFFILIATE_TAG = 'antify-21';

// 100% stable Direct Add-to-Cart routing framework for all 50 products
const freshDeals = [
    // === ₹200 DEALS CATEGORY ===
    { id: 1, category: 'rupees200', title: 'Portronics Fast Charging Cable', desc: 'Heavy-duty durable data sync charging cord for smartphones.', oldPrice: '₹399', price: '₹99', discount: '75% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B0821213P7&AssociateTag=${AFFILIATE_TAG}` },
    { id: 2, category: 'rupees200', title: 'Gizga Essentials Microfiber Cloths', desc: 'Ultra-soft absorbent cleaning cloths for laptops, tabs and screens.', oldPrice: '₹499', price: '₹149', discount: '70% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B015W9BL60&AssociateTag=${AFFILIATE_TAG}` },
    { id: 3, category: 'rupees200', title: 'ELV Desktop Mobile Stand', desc: 'Premium multi-angle adjustable desktop holder for all smartphones.', oldPrice: '₹499', price: '₹149', discount: '70% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07R451W27&AssociateTag=${AFFILIATE_TAG}` },
    { id: 4, category: 'rupees200', title: 'Syska 9W LED Base Bulb', desc: 'Energy efficient bright home lighting solution bulb base.', oldPrice: '₹250', price: '₹99', discount: '60% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00V49B8M8&AssociateTag=${AFFILIATE_TAG}` },
    { id: 5, category: 'rupees200', title: 'Cello H2O Plastic Bottle Set', desc: 'BPA-free food grade durable water bottles for daily home use.', oldPrice: '₹499', price: '₹199', discount: '60% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07N6P3N5B&AssociateTag=${AFFILIATE_TAG}` },
    { id: 6, category: 'rupees200', title: 'Pidilite Fevikwik Instant Gel', desc: 'Super strong instant adhesive glue for multiple repairs.', oldPrice: '₹150', price: '₹49', discount: '67% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07K5K621V&AssociateTag=${AFFILIATE_TAG}` },
    { id: 7, category: 'rupees200', title: 'Scotch-Brite Kitchen Sponge', desc: 'Heavy duty scrub pads for effective kitchen utensil cleaning.', oldPrice: '₹199', price: '₹89', discount: '55% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00V49B8M8&AssociateTag=${AFFILIATE_TAG}` },
    { id: 8, category: 'rupees200', title: 'Dettol Liquid Handwash Refill', desc: 'Effective germ protection handwash fluid skin gentle formula.', oldPrice: '₹199', price: '₹99', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B015W9BL60&AssociateTag=${AFFILIATE_TAG}` },
    { id: 9, category: 'rupees200', title: 'Wipro 9W Smart LED Bulb', desc: 'Energy saver lighting accent base for small room setups.', oldPrice: '₹350', price: '₹149', discount: '57% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07R451W27&AssociateTag=${AFFILIATE_TAG}` },
    { id: 10, category: 'rupees200', title: 'Classmate Octane Gel Pens', desc: 'Smooth flowing dark ink gel pens pack for regular writing.', oldPrice: '₹200', price: '₹99', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B0821213P7&AssociateTag=${AFFILIATE_TAG}` },

    // === ELECTRONICS CATEGORY ===
    { id: 11, category: 'electronics', title: 'boAt Bassheads 100 Wired Earphones', desc: 'In-ear wired earphones with super extra bass and integrated mic.', oldPrice: '₹999', price: '₹399', discount: '60% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B071Z97T21&AssociateTag=${AFFILIATE_TAG}` },
    { id: 12, category: 'electronics', title: 'SanDisk Cruzer Blade 32GB USB', desc: 'Ultra-compact portable flash drive for effortless data backups.', oldPrice: '₹650', price: '₹299', discount: '54% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B007SPF16O&AssociateTag=${AFFILIATE_TAG}` },
    { id: 13, category: 'electronics', title: 'Logitech M170 Wireless Mouse', desc: 'Reliable 2.4GHz wireless tracking precise compact mouse setup.', oldPrice: '₹895', price: '₹599', discount: '33% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B01B73D5Q4&AssociateTag=${AFFILIATE_TAG}` },
    { id: 14, category: 'electronics', title: 'TP-Link TL-WA850RE Wifi Extender', desc: 'Universal wall-plug wireless network signal booster station.', oldPrice: '₹2,999', price: '₹1,299', discount: '56% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00A0VCJPI&AssociateTag=${AFFILIATE_TAG}` },
    { id: 15, category: 'electronics', title: 'JBL C100SI Wired Headphones', desc: 'Premium signature sound quality in-ear dynamic clear bass set.', oldPrice: '₹1,299', price: '₹599', discount: '54% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B01DEWVZ2C&AssociateTag=${AFFILIATE_TAG}` },
    { id: 16, category: 'electronics', title: 'Mi 10W Fast Charger Adapter', desc: 'Safe multi-protection reliable power delivery wall block travel charger.', oldPrice: '₹599', price: '₹399', discount: '33% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08B2N5432&AssociateTag=${AFFILIATE_TAG}` },
    { id: 17, category: 'electronics', title: 'boAt Wave Call Smartwatch', desc: 'Advanced tracking sleek display layout bluetooth calling wrist wearable.', oldPrice: '₹7,990', price: '₹1,299', discount: '83% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B0B5B6D7E8&AssociateTag=${AFFILIATE_TAG}` },
    { id: 18, category: 'electronics', title: 'Zebronics Bluetooth Soundbar', desc: 'Compact dual speaker module setup for theatre room audio expansion.', oldPrice: '₹3,499', price: '₹999', discount: '71% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08Z4P3210&AssociateTag=${AFFILIATE_TAG}` },
    { id: 19, category: 'electronics', title: 'Ambrane 10000mAh Power Bank', desc: 'Dual output fast lithium polymer compact battery storage station.', oldPrice: '₹1,499', price: '₹699', discount: '53% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B09V3C9876&AssociateTag=${AFFILIATE_TAG}` },
    { id: 20, category: 'electronics', title: 'Syska 4-Way Extension Board', desc: 'Surge protector multi-plug grid with long heavy wire insulation.', oldPrice: '₹999', price: '₹449', discount: '55% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07K6T5432&AssociateTag=${AFFILIATE_TAG}` },

    // === CLOTHING CATEGORY ===
    { id: 21, category: 'clothing', title: 'Alan Jones Cotton Sweatshirt', desc: 'Premium comfortable breathable long sleeve casual winter wear.', oldPrice: '₹1,999', price: '₹599', discount: '70% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07KWSFKM4&AssociateTag=${AFFILIATE_TAG}` },
    { id: 22, category: 'clothing', title: 'Symbol Men Cotton Polo Tee', desc: 'Classic polo collar solid casual regular fit t-shirt clothing.', oldPrice: '₹1,199', price: '₹399', discount: '66% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08682F8MS&AssociateTag=${AFFILIATE_TAG}` },
    { id: 23, category: 'clothing', title: 'Lymio Casual Men Trackpants', desc: 'Regular fit athletic training joggers track pants with pockets.', oldPrice: '₹1,499', price: '₹449', discount: '70% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B09V7N6F9Z&AssociateTag=${AFFILIATE_TAG}` },
    { id: 24, category: 'clothing', title: 'Van Heusen Men Cotton Briefs', desc: 'Super combed daily elasticated waist inner clothing essential.', oldPrice: '₹599', price: '₹349', discount: '41% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08D6B7890&AssociateTag=${AFFILIATE_TAG}` },
    { id: 25, category: 'clothing', title: 'Max Men Solid Regular T-Shirt', desc: 'Soft daily crew neck premium cotton blend comfort fit tee.', oldPrice: '₹699', price: '₹299', discount: '57% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B09C6N6789&AssociateTag=${AFFILIATE_TAG}` },
    { id: 26, category: 'clothing', title: 'Puma Unisex Ankle Socks Pack', desc: 'Cushioned performance knit sport training foot accessory bundle.', oldPrice: '₹499', price: '₹299', discount: '40% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07W4N8901&AssociateTag=${AFFILIATE_TAG}` },
    { id: 27, category: 'clothing', title: 'Bata Men Formal Leather Shoes', desc: 'Durable uniform dress footwear with sleek comfort base design.', oldPrice: '₹1,999', price: '₹999', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08V3C2345&AssociateTag=${AFFILIATE_TAG}` },
    { id: 28, category: 'clothing', title: 'Levis Men Straight Fit Jeans', desc: 'Classic heavy denim vintage washed long-lasting styling pants.', oldPrice: '₹3,299', price: '₹1,499', discount: '54% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B09X4X1234&AssociateTag=${AFFILIATE_TAG}` },
    { id: 29, category: 'clothing', title: 'Adidas Sports Track Jacket', desc: 'Full zip athletic performance windcheater running active wear.', oldPrice: '₹3,999', price: '₹1,799', discount: '55% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07V2K4567&AssociateTag=${AFFILIATE_TAG}` },
    { id: 30, category: 'clothing', title: 'Wildhorn Leather Men Wallet', desc: 'Premium finish multi slot bifold pocket credit card companion.', oldPrice: '₹1,199', price: '₹399', discount: '66% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08N7C8901&AssociateTag=${AFFILIATE_TAG}` },

    // === KITCHEN CATEGORY ===
    { id: 31, category: 'kitchen', title: 'Pigeon Polypropylene Mini Chopper', desc: 'Handy manual dynamic pull-string fruit and vegetable chopper.', oldPrice: '₹495', price: '₹249', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B01LWYDEQ7&AssociateTag=${AFFILIATE_TAG}` },
    { id: 32, category: 'kitchen', title: 'Cello H2O Stainless Steel Bottle', desc: 'Durable premium mirror finish cold storage single wall flask.', oldPrice: '₹999', price: '₹399', discount: '60% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B01M3Y89B2&AssociateTag=${AFFILIATE_TAG}` },
    { id: 33, category: 'kitchen', title: 'Kuber Industries Storage Containers', desc: 'Airtight food-grade modular kitchen space organizer boxes.', oldPrice: '₹599', price: '₹249', discount: '58% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07N6P3N5B&AssociateTag=${AFFILIATE_TAG}` },
    { id: 34, category: 'kitchen', title: 'Milton Thermosteel Hot Flask', desc: 'Vacuum insulated long duration tea coffee temperature maintainer.', oldPrice: '₹1,299', price: '₹799', discount: '38% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00M85W4W2&AssociateTag=${AFFILIATE_TAG}` },
    { id: 35, category: 'kitchen', title: 'Prestige Electric Kettle 1.5L', desc: 'Automatic cut off rapid boil stainless steel liquid heater.', oldPrice: '₹1,195', price: '₹699', discount: '41% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B013UT8B8S&AssociateTag=${AFFILIATE_TAG}` },
    { id: 36, category: 'kitchen', title: 'Butterfly Premium Gas Stove', desc: 'Toughened glass top dual burner high efficiency brass setup.', oldPrice: '₹4,999', price: '₹1,999', discount: '60% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07M8X1234&AssociateTag=${AFFILIATE_TAG}` },
    { id: 37, category: 'kitchen', title: 'Borosil Glass Lunch Box Set', desc: 'Microwave safe leakproof office meal container set bags.', oldPrice: '₹1,199', price: '₹649', discount: '46% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B09B2C5678&AssociateTag=${AFFILIATE_TAG}` },
    { id: 38, category: 'kitchen', title: 'Kent 16068 Hand Milk Blender', desc: 'Powerful low noise electrical quick mix beverage whisk layout.', oldPrice: '₹1,999', price: '₹999', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08X4V8901&AssociateTag=${AFFILIATE_TAG}` },
    { id: 39, category: 'kitchen', title: 'AmazonBasics Silicone Baking Mats', desc: 'Reusable non stick sheet tray liner tool configuration panels.', oldPrice: '₹799', price: '₹399', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07W5X2345&AssociateTag=${AFFILIATE_TAG}` },
    { id: 40, category: 'kitchen', title: 'Hawkins Contura Pressure Cooker', desc: 'Hard anodized reliable performance faster uniform heating pot.', oldPrice: '₹2,100', price: '₹1,499', discount: '28% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00EICJ954&AssociateTag=${AFFILIATE_TAG}` },

    // === UTENSILS CATEGORY ===
    { id: 41, category: 'utensils', title: 'Prestige Aluminium Non-Stick Tawa', desc: 'Omni non-stick induction base premium frying durable griddle.', oldPrice: '₹1,200', price: '₹699', discount: '41% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00EICJ954&AssociateTag=${AFFILIATE_TAG}` },
    { id: 42, category: 'utensils', title: 'Signoraware Serving Ladles Set', desc: 'Heat-resistant premium non-scratch modular cooking spoon kit.', oldPrice: '₹450', price: '₹199', discount: '55% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00V4M8RBS&AssociateTag=${AFFILIATE_TAG}` },
    { id: 43, category: 'utensils', title: 'Hawkins Stainless Steel Saucepan', desc: 'Induction compatible heavy gauge tea milk cooking vessel pan.', oldPrice: '₹950', price: '₹649', discount: '31% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B00M85W4W2&AssociateTag=${AFFILIATE_TAG}` },
    { id: 44, category: 'utensils', title: 'Pigeon Non-Stick Kitchen Set', desc: 'Three piece premium cooktop kadhai frying pan flat tawa bundle.', oldPrice: '₹2,499', price: '₹1,199', discount: '52% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B01LWYDEQ7&AssociateTag=${AFFILIATE_TAG}` },
    { id: 45, category: 'utensils', title: 'Meyer Stainless Steel Kadhai', desc: 'Thick triple layer base anti scratch premium stir fry deep wok.', oldPrice: '₹2,999', price: '₹1,799', discount: '40% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B01M3Y89B2&AssociateTag=${AFFILIATE_TAG}` },
    { id: 46, category: 'utensils', title: 'Wonderchef Granite Cookware Set', desc: 'Die cast heavy construction non stick multi purpose designer pots.', oldPrice: '₹4,399', price: '₹2,199', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07N6P3N5B&AssociateTag=${AFFILIATE_TAG}` },
    { id: 47, category: 'utensils', title: 'Vinod Stainless Steel Idli Maker', desc: 'Multi tier steam container module for traditional south cooking.', oldPrice: '₹1,899', price: '₹1,149', discount: '39% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B013UT8B8S&AssociateTag=${AFFILIATE_TAG}` },
    { id: 48, category: 'utensils', title: 'Choity Potato Wave Masher', desc: 'Comfortable grip grid mesh pure smooth manual vegetable masher.', oldPrice: '₹349', price: '₹129', discount: '63% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B07M8X1234&AssociateTag=${AFFILIATE_TAG}` },
    { id: 49, category: 'utensils', title: 'Cartini Stainless Kitchen Scissors', desc: 'Razor sharp multi utility household scaling bone snipper tool.', oldPrice: '₹499', price: '₹249', discount: '50% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B09B2C5678&AssociateTag=${AFFILIATE_TAG}` },
    { id: 50, category: 'utensils', title: 'Dynamic Stainless Steel Whisks', desc: 'Heavy looping wire manual balloon cream egg blending tools.', oldPrice: '₹399', price: '₹149', discount: '62% OFF', link: `https://www.amazon.in/gp/aws/cart/add.html?Quantity.1=1&ASIN.1=B08X4V8901&AssociateTag=${AFFILIATE_TAG}` }
];

function updateDeals() {
    const indexPath = path.join(__dirname, 'index.html');
    let htmlContent = fs.readFileSync(indexPath, 'utf8');
    const dataString = JSON.stringify(freshDeals, null, 1);
    const regex = /(const dailyDeals = )\[[\s\S]*?\];/;
    htmlContent = htmlContent.replace(regex, `$1${dataString};`);
    fs.writeFileSync(indexPath, htmlContent, 'utf8');
    console.log("Success.");
}
updateDeals();
